<font size = 6><i>Numpy</i></font>

Si vous ne connaissez pas cette librairie, quelques fonctions qui peuvent être utiles pour gérer des opérations sur des tableaux.

Un tutoriel est disponible sur https://docs.scipy.org/doc/numpy/user/quickstart.html si vous souhaitez compléter ce notebook.

--

<font size= 4><I>Import</I></font>

In [1]:
import numpy as np
# numpy permet de faire facilement des calculs sur des tableaux et des matrices

<font size= 4><I>Définition simplifiée de tableau</I></font>

In [25]:
print(np.array([0.]*10)) # crée un tableau de 10 zéros
print(np.array([1.]*8)) # crée un tableau de 8 fois 1
print(np.array([8.]*9)) # crée un tableau de 9 fois 8
print(np.array([2*k+1 for k in range(18)])) # tableau des impairs jusqu'à 33

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[8. 8. 8. 8. 8. 8. 8. 8. 8.]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35]


<font size= 4><I>Équivalent à</I></font>

In [3]:
print(np.zeros(10)) # crée un tableau de 10 zéros
print(np.ones(8)) # crée un tableau de 8 fois 1
print(8*np.ones(9)) # crée un tableau de 9 fois 8
print(np.arange(1, 35, 2)) # tableau des impairs jusqu'à 33

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[8. 8. 8. 8. 8. 8. 8. 8. 8.]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33]


<font size= 4><I>Concaténation de deux tableaux</I></font>

In [4]:
num = np.array(['n','u','m'])
py = np.array(['p','y'])

conc = np.concatenate([num,py]) # tableau composé des lettres de num et des lettres de py

''.join(conc) # affichage du mot

'numpy'

<font size= 4><I>Opération sur des tableaux</I></font>

In [5]:
a = np.array([1]*5+[2]*10, dtype=np.int32)

print("a = ", a)
print("a + a = ",np.add(a,a))
print("4*a - a = ",np.subtract(4*a,a))
print("a / 4 = ",np.divide(a,4*np.ones(len(a))))

a =  [1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
a + a =  [2 2 2 2 2 4 4 4 4 4 4 4 4 4 4]
4*a - a =  [3 3 3 3 3 6 6 6 6 6 6 6 6 6 6]
a / 4 =  [0.25 0.25 0.25 0.25 0.25 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5
 0.5 ]


<font size= 4><I>Minimum et maximum</I></font>

In [6]:
np.argmax((1,2,3,4,5,6)) # indice du plus grand chiffre
np.min((1,2,3,4,5,6)) # plus petit chiffre
#Tenter d'inverser min et max

1

<font size= 4><I>Maintenant, je veux générer un tableau de nombres aléatoires</I></font>

In [7]:
print("Nombre aléatoire entre 2 et 15 : ", np.random.randint(2,15)) # à relancer plusieurs fois

Nombre aléatoire entre 2 et 15 :  2


In [8]:
alea = np.random.randint(2,15,10) # tableau de 10 nombres entre 2 et 15
alea

array([13,  4,  5,  8,  3,  2, 12, 13,  9, 11])

<font size= 4><I>Le problème, c'est que j'ai besoin d'un tableau trié...</I></font>

In [9]:
np.sort(alea)

array([ 2,  3,  4,  5,  8,  9, 11, 12, 13, 13])

<font size= 4><I>Oui, mais en décroissant...</I></font>

In [10]:
-np.sort(-alea)

array([13, 13, 12, 11,  9,  8,  5,  4,  3,  2])

<font size= 4><I>Et en plusieurs dimensions? On peut définir des matrices?</I></font>

In [11]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A =", A)
B = np.array([1,2,3])
print("B = ", B)

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
B =  [1 2 3]


<font size= 4><I>Multiplication matricielle</I></font>

In [12]:
np.multiply(A, B)

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [13]:
A * B

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

<font size= 4><I>Produit de deux tableaux/matrices</I></font>

In [14]:
np.dot(A, B)

array([14, 32, 50])

<font size= 4><I>Produit scalaire</I></font>

In [15]:
np.vdot(B, B)

14

<font size= 4><I>Transposer une matrice</I></font>

In [16]:
A.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

<font size= 4><I>Extraire sa diagonale</I></font>

In [17]:
np.diag(A)

array([1, 5, 9])

<font size= 4><I>Matrice identité</I></font>

In [18]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<font size= 4><I>Définir un espace continu</I></font>

In [19]:
np.linspace(-1,1,20) # 20 points entre -1 et 1

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

<font size= 4><I>Filtrer des valeurs respectant une condition</I></font>

In [20]:
a = np.arange(1,15,1)

np.where(a>5) # rend les indices qui vérifient la condition "est supérieur à 5"
a[np.where(a>5)] # rend les valeurs qui vérifient la condition précédente

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

<font size= 4><I>Mettre à l'échelle</I></font>

In [21]:
tab = np.array([10, 12, 15, 15,
                18, 19, -15, -16,
                -14,-18,-15,-16])

tab.reshape(3,4) # transforme le tableau initial en une matrice de 3 lignes et 4 colonnes

array([[ 10,  12,  15,  15],
       [ 18,  19, -15, -16],
       [-14, -18, -15, -16]])

In [22]:
print("A = ", A)
np.array(A.reshape(-1,1)) # transforme la matrice A en un tableau

A =  [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

<font size= 4><I>Des fonctions et des constantes en maths</I></font>

In [23]:
np.sin(0) # rend sinus(0), la fonction sinus en 0
np.cos(np.pi) # rend cosinus en pi

-1.0

<font size= 4><I>Ok, c'est fini pour numpy, bravo! Petit test, que font ces fonctions?</I></font>

In [24]:
def secret():
    alea = np.random.randint(1,30,200)
    sup = alea[np.where(alea>10)]
    return np.min(sup)

#print("Secret rend :", secret())

def enigme():
    mat =  np.arange(10,19,1).reshape(3,3)
    mat = mat - np.multiply(np.diag(mat),np.eye(3,3))
    return mat

#print("Enigme rend :", enigme())

def mystere():
    tour = np.linspace(0,2*np.pi,100)
    val = np.sin(tour)
    return tour[np.argmax(val)]

#print("Mystere rend :", mystere())

Décommentez les deux affichages pour voir les réponses! 

La suite : pandas