<font size = 6><i>Numpy</i></font>

Si vous ne connaissez pas cette librairie, quelques fonctions qui peuvent être utiles pour gérer des opérations sur des tableaux.

Un tutoriel est disponible sur https://docs.scipy.org/doc/numpy/user/quickstart.html si vous souhaitez compléter ce notebook.

--

<font size= 4><I>Import de la librairie</I></font>

In [1]:
import numpy as np

<font size= 4><I>Définition de tableau</I></font>

In [2]:
np.array((1,2,3))

array([1, 2, 3])

<font size= 4><I>Mais on peut aussi spécifier un type dans la définition de tableaux</I></font>

In [3]:
np.array([1,2,3], dtype= str)
#Par exemple, ce tableau est un tableau de chaînes de caractères

array(['1', '2', '3'], dtype='<U1')

In [4]:
np.array([1,2,3], dtype= float)
# Alors que celui-ci est un tableau de flottants

array([1., 2., 3.])

In [5]:
np.array([1000,2,3], dtype= np.int8)

array([-24,   2,   3], dtype=int8)

In [6]:
np.array([1,2,3], dtype= np.float32)

array([1., 2., 3.], dtype=float32)

<font size= 4><I>On crée un tableau monTableau</I></font>

In [7]:
monTableau = np.array([32,45,68,54])
monTableau

array([32, 45, 68, 54])

<font size= 4><I>Ce tableau a différents attributs</I></font>

In [8]:
# Longueur du tableau (pour une matrice, le nombre de lignes)
len(monTableau)

4

In [9]:
# la dimension du tableau (nbLignes, nbColonnes)
monTableau.shape

(4,)

In [10]:
#le type d'éléments qu'il contient
monTableau.dtype

dtype('int32')

In [11]:
# accéder au i-ème élément d'un tableau : monTableau[i]
monTableau[0]

32

In [12]:
# accéder aux i premiers éléments : monTableau[0:i] ou monTableau[:i]
monTableau[:2]

array([32, 45])

In [13]:
# accéder aux éléments entre les indices i et j (i inclus, j exclu): monTableau[i:j]
monTableau[1:3]

array([45, 68])

<font size= 4><I>J'aimerai générer un tableau de nombres aléatoires</I></font>

In [14]:
# Génère un tableau de 5 entiers aléatoires entre 0 et 10
monTableau = np.random.randint(0,10,5)
monTableau = np.array([4,0,6,8,5])
monTableau

array([4, 0, 6, 8, 5])

<font size= 4><I>J'aimerai que monTableau soit trié...</I></font>

In [15]:
np.sort(monTableau)

array([0, 4, 5, 6, 8])

<font size= 4><I>Oui, mais en décroissant...</I></font>

In [16]:
-np.sort(-monTableau)

array([8, 6, 5, 4, 0])

<font size= 4><I>Quelle est sa valeur minimale?</I></font>

In [17]:
np.min(monTableau)

0

<font size= 4><I>Et on la trouve à quel indice?</I></font>

In [18]:
np.argmin(monTableau)

1

<font size= 4><I>Quelle est sa valeur maximale?</I></font>

In [19]:
np.max(monTableau)

8

<font size= 4><I>Et on la trouve à quel indice?</I></font>

In [20]:
np.argmax(monTableau)

3

<font size= 4><I>Quelle est sa moyenne?</I></font>

In [21]:
np.mean(monTableau)

4.6

In [22]:
np.average(monTableau)

4.6

In [23]:
monTableau

array([4, 0, 6, 8, 5])

<font size= 4><I>Percentile </I></font>

In [24]:
np.percentile(monTableau, 50)

5.0

<font size= 4><I>Filtrer certaines valeurs du tableau </I></font>

In [25]:
monTableau[monTableau<5]

array([4, 0])

<font size= 4><I>Quelle est sa variance? Son écart-type? </I></font>

In [26]:
np.var(monTableau)
np.std(monTableau)

2.65329983228432

<font size= 4><I>Définition simplifiée de tableau</I></font>

In [27]:
print(np.array([0.]*10)) # crée un tableau de 10 zéros
print(np.array([1.]*8)) # crée un tableau de 8 éléments tous égaux à 1
print(np.array([8.]*9)) # crée un tableau de 9 éléments tous égaux à 8
print(np.array([2*k+1 for k in range(17)])) # tableau des impairs jusqu'à 33

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[8. 8. 8. 8. 8. 8. 8. 8. 8.]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33]


<font size= 4><I>Équivalent à</I></font>

In [28]:
print(np.zeros(10)) # crée un tableau de 10 zéros
print(np.ones(8)) # crée un tableau de 8 fois 1
print(8*np.ones(9)) # crée un tableau de 9 fois 8
print(np.arange(1, 35, 2)) # tableau des impairs jusqu'à 33

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[8. 8. 8. 8. 8. 8. 8. 8. 8.]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33]


<font size= 4><I>Concaténation de deux tableaux</I></font>

In [29]:
num = np.array(['n','u','m'])
py = np.array(['p','y'])

conc = np.concatenate([num,py]) # tableau composé des lettres de num et des lettres de py

conc

array(['n', 'u', 'm', 'p', 'y'], dtype='<U1')

<font size= 4><I>Opération sur des tableaux</I></font>

In [30]:
a = np.array([1]*5+[2]*10, dtype=np.int32)

print("a = ", a)
print("a + a = ",np.add(a,a))
print("4*a - a = ",np.subtract(4*a,a))
print("a / 4 = ",np.divide(a,4*np.ones(len(a))))

a =  [1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
a + a =  [2 2 2 2 2 4 4 4 4 4 4 4 4 4 4]
4*a - a =  [3 3 3 3 3 6 6 6 6 6 6 6 6 6 6]
a / 4 =  [0.25 0.25 0.25 0.25 0.25 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5
 0.5 ]


<font size= 4><I>Et en plusieurs dimensions? On peut définir des matrices?</I></font>

In [31]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A =", A)
B = np.array([1,2,3])
print("B = ", B)

A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
B =  [1 2 3]


<font size= 4><I>Multiplication matricielle</I></font>

In [32]:
np.multiply(A, B)

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [33]:
A * B

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

<font size= 4><I>Produit de deux tableaux/matrices</I></font>

In [34]:
np.dot(A, B)

array([14, 32, 50])

<font size= 4><I>Produit scalaire</I></font>

In [35]:
np.vdot(B, B)

14

<font size= 4><I>Transposer une matrice</I></font>

In [36]:
A.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

<font size= 4><I>Extraire sa diagonale</I></font>

In [37]:
np.diag(A)

array([1, 5, 9])

<font size= 4><I>Matrice identité</I></font>

In [38]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<font size= 4><I>Définir un espace continu</I></font>

In [39]:
np.linspace(-1,1,20) # 20 points entre -1 et 1

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

<font size= 4><I>Filtrer des valeurs respectant une condition</I></font>

In [40]:
a = np.arange(1,15,1)

np.where(a>5) # rend les indices qui vérifient la condition "est supérieur à 5"
a[np.where(a>5)] # rend les valeurs qui vérifient la condition précédente

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

<font size= 4><I>Mettre à l'échelle</I></font>

In [41]:
tab = np.array([10, 12, 15, 15,
                18, 19, -15, -16,
                -14,-18,-15,-16])

tab.reshape(3,4) # transforme le tableau initial en une matrice de 3 lignes et 4 colonnes

array([[ 10,  12,  15,  15],
       [ 18,  19, -15, -16],
       [-14, -18, -15, -16]])

In [42]:
print("A = ", A)
np.array(A.reshape(-1,1)) # transforme la matrice A en un tableau

A =  [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

<font size= 4><I>Des fonctions et des constantes en maths</I></font>

In [43]:
np.sin(0) # rend sinus(0), la fonction sinus en 0
np.cos(np.pi) # rend cosinus en pi

-1.0

<font size= 4><I>Import/Export</I></font>

Créez un fichier texte "loadtxt.txt" dans votre répertoire de travail, et copier le texte suivant:

1,  2,  3,  5,  6,  8, 74,  5,  5

In [44]:
np.loadtxt("loadtxt.txt", #l'adresse du fichier
           delimiter=',', # le délimiteur de texte
           dtype=np.int) #le type du tableau à importer

array([ 1,  2,  3,  5,  6,  8, 74,  5,  5])

La fonction genfromtext prend en charge les manquants, essayez de rajouter une vigule dans un fichier "genfromtxt.txt", par exemple:

1, 2, 3, 5, 6, 8, 74, 5,, 5

In [45]:
np.genfromtxt("genfromtxt.txt", #l'adresse du fichier
           delimiter=',', # le délimiteur de texte
           dtype=np.int) #le type du tableau à importer

array([ 1,  2,  3,  5,  6,  8, 74,  5, -1,  5])

<font size= 4><I>Ok, c'est fini pour numpy! Petit test, que font ces fonctions?</I></font>

In [46]:
def enigma():
    tab = np.array([41,16,10,8,1,50])
    position = np.argmin(tab)
    tab = np.sort(tab)
    return np.min(tab)+tab[position]

#print("enigma : ", enigma())

def secret():
    tab = np.array([k*5 for k in range(10)])
    tab = tab[tab<25]
    return np.mean(tab)+len(tab)

#print("secret : ", secret())

def randomness():
    alea = np.random.randint(1,30,200)
    sup = alea[np.where(alea>10)]
    return np.min(sup)

#print("randomness :", randomness())

def matr():
    mat = np.arange(10,19,1).reshape(3,3)
    upright =  np.array([[1,0,0],[0,0,0],[0,0,0]])
    mat = mat - np.multiply(np.diag(mat),np.eye(3,3)-upright)
    return mat

#print("matr rend :", matr())

def maths():
    tour = np.linspace(0,2*np.pi,100)
    val = np.sin(tour)
    return tour[np.argmax(val)]

#print("maths rend :", mystere())

Décommentez les affichages pour voir les réponses!